name: CI Stage
on:
  pull_request:
    branches:
      - "main"
  push:  
    branches:
       - "main"
jobs:
  linting:
    name: linting code + dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.2.2
      - name: install pytest
        run: pip install pytest pytest-md pytest-emoji httpx pytest-asyncio httpx  
      - name: Install dependencies
        run: |
             pip install -r requirements.txt
             pip install pylint

      - name: Run pylint
        run: |
              pylint app.py test_app.py

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile    
  unit_testing:
    name: test code
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.2.2
      - name: install pytest
        run: pip install pytest pytest-md pytest-emoji httpx pytest-asyncio httpx fastapi[standard]==0.115.13
      - name: Run pytest
        uses: pavelzw/pytest-action@v2.2.0
        with:
          verbose: true
          emoji: true
          job-summary: true
          report-title: 'Test Report'
  build_image:
    needs: unit_testing
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/hivebox:${{ github.sha }}
